version: '3'

volumes:
  pg_demo:

services:
  pg_docker:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    volumes:
      - pg_demo:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    #image: 'docker-spring-boot-postgres:latest'
    restart: always
    build: .
      #context: .
    #container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - pg_docker
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg_docker:5432/postgres
      - JAVA_OPTS -"Xmx512m"